<a href="https://colab.research.google.com/github/mooochiiii/exercise/blob/main/B%C3%A0i_t%E1%BA%ADp_v%E1%BB%81_nh%C3%A0_2_Th%E1%BB%B1c_hi%E1%BB%87n_ti%E1%BB%81n_x%E1%BB%AD_l%C3%BD_d%E1%BB%AF_li%E1%BB%87u_khi_x%C3%A2y_d%E1%BB%B1ng_m%C3%B4_h%C3%ACnh_HQTT_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
D = np.loadtxt(os.path.join("/content/drive/MyDrive", "ex1data2.txt"),
delimiter=",")
print('Kích thước của tập dữ liệu: ', D.shape)
print('Giá trị của tập dữ liệu: ')
print(D)

Kích thước của tập dữ liệu:  (47, 3)
Giá trị của tập dữ liệu: 
[[2.10400e+03 3.00000e+00 3.99900e+05]
 [1.60000e+03 3.00000e+00 3.29900e+05]
 [2.40000e+03 3.00000e+00 3.69000e+05]
 [1.41600e+03 2.00000e+00 2.32000e+05]
 [3.00000e+03 4.00000e+00 5.39900e+05]
 [1.98500e+03 4.00000e+00 2.99900e+05]
 [1.53400e+03 3.00000e+00 3.14900e+05]
 [1.42700e+03 3.00000e+00 1.98999e+05]
 [1.38000e+03 3.00000e+00 2.12000e+05]
 [1.49400e+03 3.00000e+00 2.42500e+05]
 [1.94000e+03 4.00000e+00 2.39999e+05]
 [2.00000e+03 3.00000e+00 3.47000e+05]
 [1.89000e+03 3.00000e+00 3.29999e+05]
 [4.47800e+03 5.00000e+00 6.99900e+05]
 [1.26800e+03 3.00000e+00 2.59900e+05]
 [2.30000e+03 4.00000e+00 4.49900e+05]
 [1.32000e+03 2.00000e+00 2.99900e+05]
 [1.23600e+03 3.00000e+00 1.99900e+05]
 [2.60900e+03 4.00000e+00 4.99998e+05]
 [3.03100e+03 4.00000e+00 5.99000e+05]
 [1.76700e+03 3.00000e+00 2.52900e+05]
 [1.88800e+03 2.00000e+00 2.55000e+05]
 [1.60400e+03 3.00000e+00 2.42900e+05]
 [1.96200e+03 4.00000e+00 2.59900e+05]
 

In [3]:
print('Thực hiện MinMaxScaler')
#Khởi tạo bộ điều chỉnh dữ liệu
scaler = MinMaxScaler()

Thực hiện MinMaxScaler


In [4]:
#Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
scaler.fit(D)

MinMaxScaler()

In [5]:
D = scaler.transform(D)
print('Kích thước của tập dữ liệu: ', D.shape)
print('Giá trị của tập dữ liệu: ')
print(D)
print('Lấy ra tập dữ liệu X, y')
X, y = D[:,:-1], D[:, -1]
print('Kích thước tập X: ', X.shape)
print('Kích thước vector y: ', y.shape)

Kích thước của tập dữ liệu:  (47, 3)
Giá trị của tập dữ liệu: 
[[0.34528406 0.5        0.43396226]
 [0.20628792 0.5        0.30188679]
 [0.42691671 0.5        0.37566038]
 [0.1555433  0.25       0.11716981]
 [0.59238831 0.75       0.69811321]
 [0.31246553 0.75       0.24528302]
 [0.18808605 0.5        0.27358491]
 [0.15857694 0.5        0.05490377]
 [0.145615   0.5        0.07943396]
 [0.17705461 0.5        0.13698113]
 [0.30005516 0.75       0.13226226]
 [0.31660232 0.5        0.33415094]
 [0.28626586 0.5        0.30207358]
 [1.         1.         1.        ]
 [0.11472697 0.5        0.16981132]
 [0.39933811 0.75       0.52830189]
 [0.12906784 0.25       0.24528302]
 [0.10590182 0.5        0.05660377]
 [0.48455598 0.75       0.62282642]
 [0.60093767 0.75       0.80962264]
 [0.25234418 0.5        0.15660377]
 [0.28571429 0.25       0.16056604]
 [0.20739106 0.5        0.13773585]
 [0.30612245 0.75       0.16981132]
 [0.83783784 0.5        0.76226415]
 [0.06839493 0.5        0.1509434 ]
 