<a href="https://colab.research.google.com/github/mooochiiii/exercise/blob/main/b%C3%A0i_t%E1%BA%ADp_Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.
\begin{align}
\end{align} 
numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)

- numpy.apply_along_axisLà hàm cho phép ta sử dụng hàm theo từng chiều.
- func1d : Hàm thực hiện
- axis : chọn chiều cần thực hiện
- arr : mảng cần xử lí
- *args và **kwargs đều chủ yếu được sử dụng trong định nghĩa. Hai cú pháp đặc biệt này giúp chúng ta có thể truyền bao nhiêu tham số vào hàm cũng được.
Hai hàm này thông thường ta thường bỏ qua vì trong điều kiện bình thường không cần sử dụng.

In [1]:
import numpy as np 

Câu 2: Tạo một ma trận $A_{15*17}$ có giá trị ngẫu nhiên

In [2]:
a = np.random.randint(1,100,[15,17])
a

array([[60, 68, 31, 29,  9, 98, 57, 81, 89, 30, 18, 67, 91, 18, 63,  1,
        57],
       [99, 30, 26, 56, 69, 61, 57, 69, 65, 52, 35, 22,  7, 47, 68, 99,
        29],
       [ 9, 54, 45, 33, 44,  7, 75, 73, 44, 73, 11, 41, 84, 43,  5, 93,
        92],
       [ 8, 67, 93, 74, 65, 91, 80, 53, 64, 65, 83, 45,  1, 78, 11, 63,
        92],
       [11, 91, 88, 22, 71, 34, 77, 15, 67, 24, 92, 54, 36, 16, 11, 91,
        98],
       [56, 31, 34, 90,  2, 22,  2, 72, 26,  9, 94, 65, 86, 57, 23,  5,
        88],
       [91, 44, 44, 51, 19, 35, 12, 15, 70, 53, 79, 76, 58, 23, 48, 46,
        59],
       [94, 83, 90, 29, 87, 41, 56, 35, 43, 40, 46, 93, 10,  4, 15, 60,
        25],
       [11, 23, 93, 31, 71, 70, 38, 93, 52, 41, 94, 57, 73, 42,  5, 18,
         1],
       [29, 40, 84,  4, 38, 97, 45, 51,  6,  6, 89, 47, 18, 11, 28, 26,
         3],
       [87, 79,  1, 23, 75, 93, 99, 20, 34, 26, 35, 42,  2, 43, 98, 60,
        92],
       [90, 78, 87, 12, 72, 52,  9, 66, 53, 63, 70, 11, 81, 29, 4

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def tim_gia_tri_lon_nhat(a):
    return np.max(a)

def main():
    print("\nMax : \n", np.apply_along_axis(tim_gia_tri_lon_nhat, 1, a));

if __name__ == '__main__':
    main();


Max : 
 [98 99 93 93 98 94 91 94 94 97 99 90 99 99 97]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [6]:
def tim_gia_tri_nho_nhat(a):
  return np.min(a)

def main():
    print("\nMin : \n", np.apply_along_axis(tim_gia_tri_nho_nhat,0,a));

if __name__ == '__main__':
    main();


Min : 
 [ 5 23  1  4  2  7  2 15  6  6 11 11  1  4  1  1  1]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [7]:
def tinh_tong(a):
    return np.sum(a)

def main():
    print("Sum: \n",np.apply_along_axis(tinh_tong,1,a))

if __name__ == '__main__':
    main();


Sum: 
 [ 867  891  826 1033  898  762  823  851  813  622  909  947 1003 1007
 1018]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [8]:
def tinh_tong_2(vector_a):
    sum  = 0
    for i in range(len(vector_a)):
      if (i % 2 != 0):
        sum  = sum +vector_a[i]
    return sum

def main():
    print("Sum: \n",np.apply_along_axis(tinh_tong_2, 1, a))

if __name__ == '__main__':
    main();

Sum: 
 [392 436 417 536 347 351 343 385 375 282 386 396 480 412 486]
