<a href="https://colab.research.google.com/github/mooochiiii/exercise/blob/main/b%C3%A0i_t%E1%BA%ADp_Numpy_s%E1%BB%91_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Bài 1 - Ma trận: Trong Toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu là A ∈ $R_{m×n}$ hay $A_{m×n}$ hay A = $(a_{i,j})_{m×n}$

\begin{align}
        \vec{OA} = \begin{pmatrix}
        a_{1,1} \ \ a_{1,2} \ \ ... \ \ a_{1,n}\\
        a_{2,1} \ \ a_{2,2} \ \ ... \ \ a_{2.n}\\
        \ \ \ \ ⋮ \ \ \ \ \ \ ⋮ \ \ \ \ \ \ ⋮ \ \ \ \ \ \ ⋮ \ \ \ \ \ \ \\
        a_{m,1} \ \ a_{m,2} \ \ ... \ \ a{m,n}
        \end{pmatrix}
    \end{align}
Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ $R^{7×5}$, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [2]:
A = np.random.random([7,5])
print("Ma trận A:\n",A)

Ma trận A:
 [[0.40024728 0.6989932  0.57051381 0.98562765 0.58405935]
 [0.33135047 0.1713537  0.76347537 0.96702624 0.93714652]
 [0.67832988 0.81690893 0.57592491 0.10415695 0.94128075]
 [0.70879438 0.14109817 0.42571695 0.27945256 0.93936508]
 [0.34563615 0.89596057 0.20939246 0.56704888 0.56657682]
 [0.35192375 0.21409099 0.12650552 0.54795711 0.12020572]
 [0.47565224 0.39533763 0.82427427 0.93007848 0.79349757]]


Bài 2 – Ma trận không (zero matrix): Ma trận $A_{m×n}$ được gọi là ma trận không khi $a_{i,j} = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - $A_{6×7}$. 

Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [3]:
np.zeros([6,7])
print("Ma trận không A:\n",A)

Ma trận không A:
 [[0.40024728 0.6989932  0.57051381 0.98562765 0.58405935]
 [0.33135047 0.1713537  0.76347537 0.96702624 0.93714652]
 [0.67832988 0.81690893 0.57592491 0.10415695 0.94128075]
 [0.70879438 0.14109817 0.42571695 0.27945256 0.93936508]
 [0.34563615 0.89596057 0.20939246 0.56704888 0.56657682]
 [0.35192375 0.21409099 0.12650552 0.54795711 0.12020572]
 [0.47565224 0.39533763 0.82427427 0.93007848 0.79349757]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ $R_{7×7}$, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [4]:
np.random.randint(1,20,[7,7])
print("Ma trận A:\n",A)

Ma trận A:
 [[0.40024728 0.6989932  0.57051381 0.98562765 0.58405935]
 [0.33135047 0.1713537  0.76347537 0.96702624 0.93714652]
 [0.67832988 0.81690893 0.57592491 0.10415695 0.94128075]
 [0.70879438 0.14109817 0.42571695 0.27945256 0.93936508]
 [0.34563615 0.89596057 0.20939246 0.56704888 0.56657682]
 [0.35192375 0.21409099 0.12650552 0.54795711 0.12020572]
 [0.47565224 0.39533763 0.82427427 0.93007848 0.79349757]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo $a_{i,i}$ ≠ 0 trong khi các phần tử còn lại $a_{i,j}$ = 0, ∀i ≠ j.

Sử dụng thư viện NumPy, hãy tạo một ma trận chéo $A_{6×6}$ với phần tử nằm trên đường chéo có giá trị là 15. 

Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra màn hình.

In [6]:
A = np.zeros((6,6))
np.fill_diagonal(A,15)
print("Ma trận chéo A:\n",A)

Ma trận chéo A:
 [[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông $A_{n×n}$ được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.

Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên $A_{8×8}$. 

Gợi ý: sử dụng hàm
numpy.triu(). 

Kết quả xuất ra màn hình.

In [7]:
A = np.random.randint(1,10,[8,8])
print("Ma trận tam giác trên A:\n",np.triu(A,k=0))

Ma trận tam giác trên A:
 [[7 8 5 7 5 4 7 7]
 [0 7 6 3 1 7 5 1]
 [0 0 1 3 7 8 8 8]
 [0 0 0 4 2 3 1 2]
 [0 0 0 0 6 8 1 2]
 [0 0 0 0 0 5 8 6]
 [0 0 0 0 0 0 2 8]
 [0 0 0 0 0 0 0 2]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [8]:
A = np.random.randint(1,10,[8,8])
print("Ma trận tam giác dưới A:\n",np.tril(A,k=0))

Ma trận tam giác dưới A:
 [[4 0 0 0 0 0 0 0]
 [4 9 0 0 0 0 0 0]
 [6 2 5 0 0 0 0 0]
 [3 5 8 3 0 0 0 0]
 [2 1 4 2 6 0 0 0]
 [1 7 7 8 5 1 0 0]
 [9 4 7 2 6 6 9 0]
 [8 5 5 3 4 9 8 4]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị $I_n$ có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
$I_9$
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [9]:
#cách 1

print("Ma trận đơn vị I9:\n",np.identity(9))

#cách 2

print("Ma trận đơn vị I9:\n",np.eye(9))

Ma trận đơn vị I9:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Ma trận đơn vị I9:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:
- Phép cộng ma trận: $A_{m×n} + B_{m×n} = C_{m×n}$. Hãy sinh ngẫu nhiên 2 ma trận có kích thước
6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.
- Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 1 ma trận có kích thước
5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất
ra màn hình.
- Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép
chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.
- Phép nhân 2 ma trận: $A_{m×n} + B_{m×n} = C_{m×n}$. Hãy sinh ngẫu nhiên 2 ma trận $A_{5×7} và B_{7×3}$,
tiến hành nhân 2 ma trận này để thu được ma trận $C_{5×3}$. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()
- Ma trận khả nghịch: ma trận vuông $A_{n×n}$ 
gọi là khả nghịch (hay không suy biến) nếu tồn
tại một ma trận vuông $B_{n×n}$ sao cho A ∙ B = $I_n$ . Khi này, B được gọi là ma trận nghịch
đảo của A và ký hiệu là A
−1
. Cho ma trận $A_{5×7}$, hãy tính ma trận khả nghịch của A. 

Gợi ý: sử dụng hàm numpy.linalg.inv()

In [10]:
#cộng hai ma trận

A = np.random.randint(1,10,[6,7])
B = np.random.randint(1,10,[6,7])
print("A+B:\n",A+B)

#Nhân vô hướng

A = np.random.randint(1,5,[5,8])
print(A)
n = int(input("Nhân ma trận với: "))
print("Kết quả của phép nhân vô hướng A với",n,"là\n",A*n)

#Chuyển vị

A = np.random.randint(1,10,[3,7])
print("Ma trận ban đầu:\n",A)
print("Chuyển vị:\n",A.T)

#Nhân hai ma trận

A = np.random.randint(1,5,[5,7])
print("Ma trận A:\n", A)
B = np.random.randint(1,5,[7,3])
print("Ma trận B:\n", B)
print("Nhân hai ma trận A và B:\n",A.dot(B))

#Ngoài ra: A @ B cũng là phép nhân hai ma trận A và B

#Ma trận nghịch đảo

A = np.random.randint(1,5,[5,5])
A_i = np.linalg.pinv(A)
print("Ma trận ban đầu\n",A)
print("Ma trận nghịch đảo\n",A_i)

A+B:
 [[ 6  3  5 13  9  8  6]
 [18  6  9  9 15 10  7]
 [12 15  6 13  2 10  7]
 [14 11  9 11 11 12  8]
 [14  9  9 11  9 11 11]
 [16 11 12  9  9  5  5]]
[[1 2 4 4 4 4 4 2]
 [4 3 2 4 2 1 3 3]
 [3 4 3 4 3 1 1 3]
 [3 3 1 1 2 1 1 1]
 [2 3 2 3 3 2 3 1]]
Nhân ma trận với: 2
Kết quả của phép nhân vô hướng A với 2 là
 [[2 4 8 8 8 8 8 4]
 [8 6 4 8 4 2 6 6]
 [6 8 6 8 6 2 2 6]
 [6 6 2 2 4 2 2 2]
 [4 6 4 6 6 4 6 2]]
Ma trận ban đầu:
 [[2 3 4 2 6 3 3]
 [7 2 5 6 5 9 9]
 [6 7 7 4 4 1 4]]
Chuyển vị:
 [[2 7 6]
 [3 2 7]
 [4 5 7]
 [2 6 4]
 [6 5 4]
 [3 9 1]
 [3 9 4]]
Ma trận A:
 [[3 4 1 1 1 2 1]
 [2 2 3 1 3 1 4]
 [2 3 3 3 1 1 3]
 [4 4 2 4 2 3 4]
 [4 1 4 3 2 4 1]]
Ma trận B:
 [[3 2 4]
 [4 4 1]
 [1 3 3]
 [2 1 2]
 [1 4 1]
 [3 4 4]
 [4 4 4]]
Nhân hai ma trận A và B:
 [[39 42 34]
 [41 54 44]
 [43 48 43]
 [65 70 64]
 [44 55 57]]
Ma trận ban đầu
 [[3 3 3 1 2]
 [2 4 1 1 1]
 [3 2 4 3 1]
 [1 4 3 1 3]
 [2 3 1 3 1]]
Ma trận nghịch đảo
 [[ 0.65060241 -0.13253012 -0.21686747 -0.37349398  0.1686747 ]
 [-0.36144578  0.5180

Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau
- Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1
vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.
- Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên
1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [11]:
#Vector hàng

A = np.random.randint(1,10,[1,8])
print(A)
A.shape

#Vector cột

A = np.random.randint(1,10,[8,1])
print(A)
A.shape

[[7 7 2 4 7 8 9 1]]
[[3]
 [5]
 [7]
 [5]
 [8]
 [5]
 [9]
 [7]]


(8, 1)

bài 10:

In [12]:
import numpy as np
A = np.random.randint(1,10,[3,3])
y = np.random.randint(1,5)
A_i = np.linalg.pinv(A)
x = np.dot(A_i, y)
print(x)

[[-0.69387755  0.53061224  0.32653061]
 [ 1.2244898   0.12244898 -0.69387755]
 [ 0.32653061 -0.36734694  0.08163265]]
