<a href="https://colab.research.google.com/github/mooochiiii/exercise/blob/main/numpy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):


*   np.arrange()
*   np.linspace()

*   np.logspace()

*   np.random.rand()

Ghi chú: sau mỗi lần sinh ra giá trị cho vector, hãy cho biết số chiều của vector được sinh ra và
số chiều của vector chuyển vị của vector đó; cho biết kích thước của vector a và vector chuyển vị
của vector a.
Gợi ý: tham khảo ndim và shape.










In [2]:
import numpy as np

# np.arrange()

a =np.arange(1,8)
print(a,"\n")
print(a.ndim,"\n")
print(a.T.ndim,"\n")
print(a.shape,"\n")
print(a.T.shape)

# np.linspace()

b=np.linspace(0,6,7)
print(b,"\n")
print(b.ndim,"\n")
print(b.T.ndim,"\n")
print(b.shape,"\n")
print(b.T.shape,"\n")

# np.logspace()

c=np.logspace(1,7,7)
print(c)
print(c.ndim,"\n")
print(c.T.ndim,"\n")
print(c.shape,"\n")
print(c.T.shape,"\n")

# np.random.rand()

d=np.random.rand(7)
print(d)
print(d.ndim,"\n")
print(d.T.ndim,"\n")
print(d.shape,"\n")
print(d.T.shape)

[1 2 3 4 5 6 7] 

1 

1 

(7,) 

(7,)
[0. 1. 2. 3. 4. 5. 6.] 

1 

1 

(7,) 

(7,) 

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07]
1 

1 

(7,) 

(7,) 

[0.02016502 0.47022954 0.25366086 0.99231563 0.46872223 0.3454397
 0.05356431]
1 

1 

(7,) 

(7,)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận $A_{10x7}$ với giá trị các phần tử của ma trận A
được sinh bởi:


*   np.arrange()
*   np.linspace()

*   np.logspace()

*   np.random.rand()

Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:



*   Số chiều và kích thước của ma trận A và ma trận $A^T$



In [3]:
#ham arange()
a = np.arange(1,71).reshape(10,7)
print(a,"\n")
print(a.ndim,"\n")
print(a.T.ndim,"\n")
print(a.shape,"\n")
print(a.T.shape)

#ham linspace()
a = np.linspace(0,70,num=70).reshape(10,7)
print(a,"\n")
print(a.ndim,"\n")
print(a.T.ndim,"\n")
print(a.shape,"\n")
print(a.T.shape)

#hamlogspace()
a = np.logspace(0,70,num=70).reshape(10,7)
print(a,"\n")
print(a.ndim,"\n")
print(a.T.ndim,"\n")
print(a.shape,"\n")
print(a.T.shape)

#ham random.rand()
a = np.random.rand(10,7)
print(a)
print(a.ndim,"\n")
print(a.T.ndim,"\n")
print(a.shape,"\n")
print(a.T.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70]] 

2 

2 

(10, 7) 

(7, 10)
[[ 0.          1.01449275  2.02898551  3.04347826  4.05797101  5.07246377
   6.08695652]
 [ 7.10144928  8.11594203  9.13043478 10.14492754 11.15942029 12.17391304
  13.1884058 ]
 [14.20289855 15.2173913  16.23188406 17.24637681 18.26086957 19.27536232
  20.28985507]
 [21.30434783 22.31884058 23.33333333 24.34782609 25.36231884 26.37681159
  27.39130435]
 [28.4057971  29.42028986 30.43478261 31.44927536 32.46376812 33.47826087
  34.49275362]
 [35.50724638 36.52173913 37.53623188 38.55072464 39.56521739 40.57971014
  41.5942029 ]
 [42.60869565 43.62318841 44.63768116 45.65217391 46.66666667 47.68115942
  48.69565217]
 [49.71014493 50.72463768 51.73913043 52.75362319 53.76811594 54.7826087
  55.79710145]
 [56.8115942  57.826

Câu 3: Sử dụng thư viện Numpy, hãy:



*   Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
*   Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())



In [4]:
#chuyen ma tran o cau 2 thanh vector
print("chuyen ma tran o cau 2 thanh vector")
a.flatten()

#chuyen vector thanh ma tran
print("chuyen vector thanh ma tran")
a.reshape(10,7)

chuyen ma tran o cau 2 thanh vector
chuyen vector thanh ma tran


array([[0.18952698, 0.81917756, 0.34002246, 0.08149204, 0.77727062,
        0.8517896 , 0.53841796],
       [0.81286956, 0.97481824, 0.30888773, 0.88581607, 0.43602223,
        0.3334135 , 0.55660597],
       [0.24493721, 0.15090085, 0.17204807, 0.41636672, 0.92615321,
        0.74495043, 0.17497948],
       [0.19622563, 0.34294527, 0.16814905, 0.40316365, 0.30669912,
        0.45681422, 0.53062803],
       [0.63231316, 0.59124392, 0.50595972, 0.03160739, 0.36338024,
        0.98604205, 0.18001464],
       [0.20898228, 0.0889662 , 0.60498641, 0.74214356, 0.95791692,
        0.7486299 , 0.25334168],
       [0.92439157, 0.85567467, 0.32821885, 0.34587625, 0.60724142,
        0.46982525, 0.88474384],
       [0.18913671, 0.13822219, 0.69407215, 0.77384848, 0.22174235,
        0.24369448, 0.43181506],
       [0.31804109, 0.72562874, 0.33581414, 0.60324429, 0.42276903,
        0.70581675, 0.62356744],
       [0.68957019, 0.13245033, 0.72140319, 0.9114536 , 0.38985032,
        0.3834655 , 0.4

Câu 4: Sử dụng thư viện Numpy, hãy:



*   Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();

*   Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
*   Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).




In [5]:
a = np.logspace(0,150,num=150).reshape(10,15)
print(a)
print("hang thu 3 cua ma tran a: ", a[2:3])
print("cot thu 5 cua ma tran a: ", a[:,4:5])

[[1.00000000e+000 1.01557362e+001 1.03138977e+002 1.04745224e+003
  1.06376485e+004 1.08033152e+005 1.09715619e+006 1.11424288e+007
  1.13159567e+008 1.14921870e+009 1.16711619e+010 1.18529241e+011
  1.20375170e+012 1.22249846e+013 1.24153719e+014]
 [1.26087241e+015 1.28050875e+016 1.30045090e+017 1.32070362e+018
  1.34127175e+019 1.36216020e+020 1.38337396e+021 1.40491810e+022
  1.42679775e+023 1.44901815e+024 1.47158460e+025 1.49450249e+026
  1.51777730e+027 1.54141458e+028 1.56541998e+029]
 [1.58979923e+030 1.61455815e+031 1.63970266e+032 1.66523876e+033
  1.69117254e+034 1.71751022e+035 1.74425806e+036 1.77142246e+037
  1.79900992e+038 1.82702700e+039 1.85548042e+040 1.88437696e+041
  1.91372352e+042 1.94352711e+043 1.97379486e+044]
 [2.00453398e+045 2.03575182e+046 2.06745584e+047 2.09965360e+048
  2.13235280e+049 2.16556124e+050 2.19928686e+051 2.23353771e+052
  2.26832196e+053 2.30364794e+054 2.33952406e+055 2.37595891e+056
  2.41296118e+057 2.45053971e+058 2.48870348e+059]
 [2.

Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A

Gợi ý: tham khảo hàm apply_along_axis() đã học ở bài trước.

In [6]:
#np.mean()
x = np.array([1,2,3,4,5])
print(np.mean(x))

#np.median()
X = np.array([2, 5, 3, 4,1, 7])
print(np.median(X))

#np.nanmedian()
y = np.array([2, 5, 3, 4,1, 7,np.nan])
print(np.nanmedian(y))

#np.var()
Y = np.array([1,2,4,6,7])
print(np.var(Y))

#np.std()
print(np.std(Y))

#GT trung binh
import numpy as np
a = np.arange(1,151).reshape(15,10)
print(a)
print(np.mean(a,axis=1))
print(np.mean(a,axis=0))

#GT trung vi
a = np.arange(1,151).reshape(15,10)
print(a)
print(np.median(a,axis=1))
print(np.median(a,axis =0))

#GT phuong sai
a = np.arange(1,151).reshape(15,10)
print(a)
print(np.var(a,axis=1))
print(np.var(a,axis =0))

#GT do lech chuan
a = np.arange(1,151).reshape(15,10)
print(a)
print(np.std(a,axis=1))
print(np.std(a,axis =0))

3.0
3.5
3.5
5.2
2.280350850198276
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]
[  5.5  15.5  25.5  35.5  45.5  55.5  65.5  75.5  85.5  95.5 105.5 115.5
 125.5 135.5 145.5]
[71. 72. 73. 74. 75. 76. 77. 78. 79. 80.]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43